### ISSUE TITLE
COSMIC App Store MVP Issue List

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-store#53]
- [x] pop-os/cosmic-store#51 
- [x] pop-os/cosmic-store#56
- [x] pop-os/cosmic-store#47 
- [ ] pop-os/cosmic-store#55
- [ ] pop-os/cosmic-store#52
- [ ] pop-os/cosmic-store#54
- [x] pop-os/repoman#118

**Comment by WatchMkr** [comment]
Closing. Tracking with milestones now.
